config/routes.rb
Rails.application.routes.draw do
  resources :alarms do
    resources :upvotes, only: :create
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alarm.rb
class Alarm < ApplicationRecord
  has_one :upvote, dependent: :destroy

  validates :message, presence: true
  before_save :upcase_message
  after_create :push_message

  BELLBIRD_WEBHOOK = "https://bellbird.joinhandshake-internal.com/push"

  def upcase_message
    self.message = self.message.upcase
  end

  def push_message
    url = BELLBIRD_WEBHOOK
    headers = { 'Content-Type' => 'application/json' }
    res = APIService.new(url).post_request(headers, { alarm_id: self.id })
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :alarm

  validates :alarm, presence: true
  before_save :increment_vote_count

  def increment_vote_count
    self.vote_count.nil? ?  self.vote_count = 1 : self.vote_count += 1
  end
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  before_action :set_alarm, only: [:show, :edit, :update, :destroy]

  # GET /alarms
  # GET /alarms.json
  def index
    @alarms = Alarm.all.order('created_at DESC').includes(:upvote)
  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show
  end

  # GET /alarms/new
  def new
    @alarm = Alarm.new
  end

  # GET /alarms/1/edit
  def edit
  end

  # POST /alarms
  # POST /alarms.json
  def create
    @alarm = Alarm.new(alarm_params)

    respond_to do |format|
      if @alarm.save
        format.html { redirect_to @alarm, notice: 'Alarm was successfully created.' }
        format.json { render :show, status: :created, location: @alarm }
      else
        format.html { render :new }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alarms/1
  # PATCH/PUT /alarms/1.json
  def update
    respond_to do |format|
      if @alarm.update(alarm_params)
        format.html { redirect_to @alarm, notice: 'Alarm was successfully updated.' }
        format.json { render :show, status: :ok, location: @alarm }
      else
        format.html { render :edit }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarms/1
  # DELETE /alarms/1.json
  def destroy
    @alarm.destroy
    respond_to do |format|
      format.html { redirect_to alarms_url, notice: 'Alarm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_alarm
      @alarm = Alarm.find(params[:id])
    end

    def alarm_params
      params.require(:alarm).permit(:message)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  before_action :set_alarm, only: [:create]
  # POST /alarms/:alarm_id/upvotes
  # POST /alarms/:alarm_id/upvotes.json
  def create
    @upvote = Upvote.where(alarm_id: @alarm.id).first
    
    unless @upvote
      @upvote = Upvote.new(alarm_id: @alarm.id)
    end

    respond_to do |format|
      if @upvote.save
        format.html { redirect_to @alarm, notice: 'Alarm was successfully upvoted.' }
        format.json { render :show, status: :created, location: @alarm }
      else
        format.html { render :new }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_alarm
      @alarm = Alarm.find(params[:alarm_id])
    end
end

app/helpers/alarm_upvotes_helper.rb
module AlarmUpvotesHelper
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alarms/_form.html.erb
<%= form_with(model: alarm, local: true) do |form| %>
  <% if alarm.errors.any? %>
    <div id="alert alert-danger error_explanation">
      <h2><%= pluralize(alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
      <% alarm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alarms/edit.html.erb
<h1>Editing Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Show', @alarm %> |
<%= link_to 'Back', alarms_path %>

app/views/alarms/index.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<h1>Alarms</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <div class="container">
      <% @alarms.each do |alarm| %>
        <div class="row">
            <div class="col-sm-2">
              <%= link_to alarm_upvotes_path(alarm), :method=> :post do%>
                  <i class="far fa-arrow-alt-circle-up">
                    <%= alarm.upvote.present? ? alarm.upvote.vote_count : 0 %>
                  </i>
              <% end %>
            </div>
            <div class="col-sm-7">
              <%= alarm.message %>
            </div>
            <div class="col-sm-1">
              <%= link_to 'Show', alarm %>
            </div>
            <div class="col-sm-1">
              <%= link_to 'Edit', edit_alarm_path(alarm) %>
            </div>
            <div class="col-sm-1">
              <%= link_to 'Destroy', alarm, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>

        </div>
      <% end %>
    </div>
  </tbody>
</table>

<br>

<%= link_to 'New Alarm', new_alarm_path %>

app/views/alarms/new.html.erb
<h1>New Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Back', alarms_path %>

app/views/alarms/show.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<p>
  <strong>Message:</strong>
  </br>
  <%= @alarm.message %>

  <%= link_to alarm_upvotes_path(@alarm), :method=> :post do%>
    <i class="far fa-arrow-alt-circle-up">
      <%= @alarm.upvote.present? ? @alarm.upvote.vote_count : 0 %>
    </i>
  <% end %>
</p>

<%= link_to 'Edit', edit_alarm_path(@alarm) %> |
<%= link_to 'Back', alarms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bellbird</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>